spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.database}
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: ${APP_PROFILE:local}