spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.database}
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: ${APP_PROFILE:local}

server:
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health" ]
  endpoint:
    health:
      show-details: always
