apiVersion: v1
kind: Pod
metadata:
  name: db-techfood
  labels:
    app: db-techfood
spec:
  containers:
    - name: container-db-techfood
      image: mysql
      #command: ["--default-authentication-plugin=mysql_native_password"]
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef: 
            name: db-configmap
